export const questions = [
  // Fácil
  { question: "¿Qué métrica indica el costo promedio que pagas por cada clic en tu anuncio?", options: ["CPM", "CTR", "CPC", "ACOS"], correctAnswer: 2, explanation: "El CPC (Costo Por Clic) se calcula dividiendo la inversión total por el número de clics.", difficulty: "facil" },
  { question: "Para medir posicionamiento de marca y exposición, ¿qué métrica debe optimizarse?", options: ["CPA", "CPM", "CPC", "CPL"], correctAnswer: 1, explanation: "El CPM (Costo por Mil Impresiones) te ayuda a maximizar tu visibilidad a gran escala en estrategias de branding.", difficulty: "facil" },
  { question: "¿Qué indica la precisión de tu anuncio, es decir, qué porcentaje de la gente decide al menos verlo de cerca?", options: ["ACOS", "ROAS de Búsqueda", "CTR", "CVR"], correctAnswer: 2, explanation: "El CTR (Click-Through Rate) muestra cuántos clics obtuviste por la cantidad de veces que se imprimió tu anuncio.", difficulty: "facil" },
  { question: "La Tasa de Conversión (CVR) representa:", options: ["Las impresiones brutas del anuncio", "Qué porcentaje de los clics se convirtieron en compras", "El costo por lograr que un cliente vuelva", "Segmentación fallida"], correctAnswer: 1, explanation: "Una buena tasa de conversión (CVR) significa que tu landing page o página de producto convence efectivamente al usuario de comprar.", difficulty: "facil" },
  { question: "¿Qué es una 'Impresión' en publicidad digital?", options: ["El costo de imprimir folletos", "La cantidad de veces que se muestra un anuncio en la pantalla de un usuario", "La sensación que le deja la marca al comprador", "Un clic exitoso"], correctAnswer: 1, explanation: "Cada vez que tu anuncio carga y se despliega en pantalla es contabilizado como 1 Impresión.", difficulty: "facil" },
  { question: "En Mercado Ads, ¿Qué es el 'Presupuesto Diario'?", options: ["Lo que el usuario gasta al comprar", "El límite de dinero que Mercado Libre te presta para publicidad", "El monto máximo preestablecido que estás dispuesto a invertir por día en una campaña", "Un seguro mensual"], correctAnswer: 2, explanation: "Establecer tu presupuesto diario controla tus recursos financieros limitando lo máximo a consumir en el día publicitario.", difficulty: "facil" },
  { question: "¿Qué hace que la publicidad dentro de un Marketplace (como Mercado Libre) sea tan efectiva?", options: ["No tiene competencia de precios", "Hay pauta en la televisión de forma gratis", "Alcanzas a usuarios con una fuerte intención de búsqueda y de compra real", "Genera likes automáticamente"], correctAnswer: 2, explanation: "Los usuarios ya están navegando listos para comprar, impactarlos ahí potencia la efectividad radicalmente frente a otras redes sociales.", difficulty: "facil" },
  { question: "¿Qué efecto tiene poner en 'Pausa' una campaña publicitaria?", options: ["Los anuncios se siguen mostrando, pero gratis", "Detiene al instante la entrega de anuncios y el consumo de inversión", "Reduce el costo a la mitad", "Los envíos se vuelven gratis"], correctAnswer: 1, explanation: "Pausar es la acción instantánea para cortar o detener el ritmo de gasto si tienes que restructurar métricas.", difficulty: "facil" },
  { question: "¿Qué significa el término 'Clic' en nuestro contexto publicitario?", options: ["Cuando un cliente agrega al carrito", "La acción donde el usuario oprime el anuncio y es llevado al producto/página", "Una interacción telefónica", "El pago de un producto en cuotas"], correctAnswer: 1, explanation: "El clic comprueba que tu pieza creativa o banner logró atraer la suficiente atención del usuario.", difficulty: "facil" },
  { question: "¿Cuál de los siguientes es el propio ecosistema de soluciones publicitarias integrado de Mercado Libre?", options: ["Mercado Shops", "Mercado Envíos", "Mercado Pago", "Mercado Ads"], correctAnswer: 3, explanation: "Mercado Ads nuclea todas las herramientas (Performance, Display, etc.) para acelerar ventas de anunciantes en MELI.", difficulty: "facil" },

  // Intermedio
  { question: "¿Qué significan las siglas ROAS?", options: ["Return On Ad Spend (Retorno sobre Inversión Publicitaria)", "Rate of Advertising Sales", "Return On Actual Sales", "Revenue over Ad Spend"], correctAnswer: 0, explanation: "El ROAS mide los ingresos generados por cada peso o dólar invertido en publicidad.", difficulty: "intermedio" },
  { question: "¿Qué nos muestra el 'Share of Voice' (SOV)?", options: ["El porcentaje de mercado publicitario y visibilidad que logramos frente a todos nuestros competidores", "Porcentaje de quejas al call-center por un producto defectuoso", "Búsquedas realizadas por micrófono", "Costos en campañas auditivas"], correctAnswer: 0, explanation: "Un alto Share of Voice significa que tu marca domina la cuota de pantalla frente a las demás alternativas.", difficulty: "intermedio" },
  { question: "¿Qué término hace referencia a la adquisición de tráfico logrando una venta, acción o subscripción?", options: ["CPV", "CPA", "CPM", "CTa"], correctAnswer: 1, explanation: "El CPA (Costo Por Adquisición) se basa en la meta final de negocio o performance máxima para registrar leads o conversiones reales.", difficulty: "intermedio" },
  { question: "¿Para qué sirve 'Product Ads' dentro de Mercado Libre?", options: ["Enviar correos publicitarios masivos", "Potenciar y apalancar posiciones destacadas del producto dentro de búsquedas relevantes en el sitio", "Aparecer en carteleras de vía pública", "Comprar inventario remanente de Youtube"], correctAnswer: 1, explanation: "La herramienta Product Ads mejora la exposición del catálogo empujando los ítems a los top slots dentro de las subpáginas o listados.", difficulty: "intermedio" },
  { question: "¿Qué rige y evalúa el modelo de 'Subasta' (Bidding) detrás de Product Ads?", options: ["Un algoritmo donde solo importa tener el producto más barato a la venta", "Un sistema donde ganas exposición combinando e impactando tu límite de oferta (CPC) y la calidad intrínseca de tu anuncio", "Pagar una cuota fija manual mensual", "El mejor vendedor siempre gana el primer lugar sin pagar Ads"], correctAnswer: 1, explanation: "Es un balance vital; por más que pagues mucho CPC, si tu Ad no tiene relevancia orgánica (Calidad), pierdes la subasta.", difficulty: "intermedio" },
  { question: "¿Qué es una estrategia 'Always On'?", options: ["Tener la tienda online sin contraseñas locales", "Campañas tácticas que solo levantan alcance durante eventos únicos como Hot Sale", "Tener publicidad activa de forma ininterrumpida para abarcar la demanda constante", "Apagar campañas y dejarlas offline en horarios nocturnos"], correctAnswer: 2, explanation: "Estar siempre prendido asegura que ningún comprador potencial de tu nicho se esfume por falta de publicidad activa diaria.", difficulty: "intermedio" },
  { question: "¿A qué etapa del Pipeline o Funnel (Embudo) ataca preferentemente Product Ads?", options: ["Upper Funnel (Awareness/Notoriedad a gran escala)", "Lower Funnel (Conversión y Ventas transaccionales directas)", "Mid Funnel Exclusivo (Consideración Pura)", "Soporte de fidelización Post-compra y Mails"], correctAnswer: 1, explanation: "Dado que el cliente está buscando con alta intención un ítem, Product Ads cierra directamente su viaje con el clic y posterior compra local.", difficulty: "intermedio" },
  { question: "Si queremos aparecer ante intenciones específicas del cliente que redacta en el buscador, deberíamos utilizar estratégicamente:", options: ["Palabras Clave (Keywords)", "Emojis llamativos en el banner", "Pauta televisiva local", "Display Banners masivos del sitio"], correctAnswer: 0, explanation: "Alinear palabras clave como match garantiza que te cruces cuando el cliente tipée tu rubro.", difficulty: "intermedio" },
  { question: "¿Por qué Mercado Ads califica la 'Relevancia' del anuncio al decidir el ganador final de una subasta de impresión?", options: ["Para cobrarle siempre al vendedor más adinerado", "Para garantizar que el comprador vea publicidad acorde y no frustrante a lo que busca, logrando fluidez de ecosistema", "Porque bloquea las publicaciones con envío gratis automático", "Para descartar productos provenientes del exterior arbitrariamente"], correctAnswer: 1, explanation: "La Relevancia prioriza el engagement del usuario: si busca Laptops y tú le muestras Lavadoras, empeoras brutalmente la experiencia de compra.", difficulty: "intermedio" },
  { question: "En métricas publicitarias ¿A qué llamamos y qué se entiende por 'Ventana de Atribución'?", options: ["El margen y ventana de tiempo dictaminado en el que un clic pasado sigue influyendo e hilvanando la adjudicación y el mérito de una venta", "El momento o día del mes en que se facturan los consumos en tarjetas", "El recuadro o popup limitante que bloquea un anuncio emergente publicitario", "Tiempo final de garantía y vida útil de inventario"], correctAnswer: 0, explanation: "Define cuánto tiempo (ej: 7 días, 14 días) un evento de pago (la compra) pertenece y es acreditado lógicamente por un Clic en un Ad anterior.", difficulty: "intermedio" },

  // Difícil
  { question: "¿Cómo se mide la salud de la inversión en campañas de Performance en Mercado Libre?", options: ["Tasa de rebote orgánico", "ACOS", "Click-Through Rate exclusivo", "CPV"], correctAnswer: 1, explanation: "El ACOS (Advertising Cost of Sales) refleja qué porcentaje de tu dinero generado en la venta consumió la publicidad.", difficulty: "dificil" },
  { question: "¿Qué es el Retargeting?", options: ["Anunciar exclusivamente a usuarios que ya mostraron interés previo en tu producto o marca", "Configurar los costos a un límite mensual", "Cambiar la agencia creativa regularmente", "Eliminar palabras clave negativas"], correctAnswer: 0, explanation: "El Retargeting permite volver a capturar la atención de usuarios potenciales más proclives a concretar.", difficulty: "dificil" },
  { question: "¿Cuál es el principal valor de usar 'Custom Audiences' (Audiencias Diferenciadas)?", options: ["Te obligan a mantener siempre el mismo banner", "Garantizan siempre 100% de conversión cruzada", "Permiten apuntar a consumidores a partir de sus intenciones reales y comportamientos de navegación previos predominantes", "Son más baratas siempre"], correctAnswer: 2, explanation: "Con Custom Audiences le llegas directamente a aquel cliente altamente relevante usando Inteligencia de los sitios en la red de Mercado Ads.", difficulty: "dificil" },
  { question: "Dentro de la medición de Display Ads, Viewability garantiza estrictamente que...", options: ["El anuncio corrió masivamente en TV sin interrupción", "El banner tuvo la debida visibilidad parcial de pixeles en foco de pantalla por los segundos formativos estandarizados por la industria", "El banner generó una viralización social inmediata", "El archivo de arte y vector se descargó ultra rápido en la SD local del móvil del navegante"], correctAnswer: 1, explanation: "Viewability certifica para las grandes agencias que sí obtuvieron presencia de ojos en el plano digital de su mercado meta.", difficulty: "dificil" },
  { question: "¿Qué métrica vital usarías si estás comprando en programático y solo exiges optimizar tu pago basándote puntualmente en impresiones que validamente entraron en la vista real del humano?", options: ["CTR general de las Imágenes", "CPV Base", "vCPM (Cost per viewable 1,000 impressions)", "Mediana Frecuencia Absoluta"], correctAnswer: 2, explanation: "Diferente al simple CPM, el vCPM destina rigor de auditoría para pagar por exposición confirmada on-screen, fundamental en Brand Awareness.", difficulty: "dificil" },
  { question: "Para que el pilar predictivo de Machine Learning de la campaña madure y salga exitosamente de su 'fase ciega de aprendizaje', estadísticamente carecerá y necesitará de:", options: ["Exceder radicalmente el presupuesto del Marketplace", "Simplificar e inhibir palabras a usar un nombre más críptico o corto", "Llegar y englobar rápidamente un gran volumen de tracción algorítmica constante como clics o conversiones en ventana inicial", "Usar arbitrariamente todas las intenciones posibles como palabras clave negativas cruzadas"], correctAnswer: 2, explanation: "El modelo predictivo no es mago; requiere combustible o 'Data'. Ese dato son las conversiones. Más data = aprendizaje superado y optimizado.", difficulty: "dificil" },
  { question: "El arsenal de 'First-Party Data' empaquetado y crudo de Mercado Libre rompe la media del e-commerce moderno y la industria ya que...", options: ["Lee sin cifrar el tracking geo satelital profundo o chats genéricos del browser", "Rastrea localmente con contraseñas bancarias y burocracia ajena o federal", "Clasifica y permite proyectar e influir basándose en comportamientos verídicos, pagos y propensiones finalizadas de compras concretas de la red", "Permite ver e intervenir nativamente la historia completa de a qué otras páginas externas entra el comprador luego"], correctAnswer: 2, explanation: "Al no depender de redes de terceros, MELI posee la certeza cruda e inequívoca de si compraron, cuánto y cuándo interesó; un pilar en un futuro sin 3rd-party cookies.", difficulty: "dificil" },
  { question: "Si tu empresa produce de cero y vende Zapatillas Exclusivas de asfalto y deportivas, ¿Por qué estratégicamente apilarías 'Usadas' como Palabra Clave Negativa Exacta dentro de tu matriz?", options: ["Porque restringe contundentemente tirar y malgastar presupuesto con clics transeúntes de usuarios cazadores abocados meramente a mercado secundario", "Para desviar algorítmicamente envíos de correos hacia el país lejano de destino", "Por que Mercado Ads bloquea automáticamente y penaliza publicitar artículos importados indirectamente", "Para inflar e ilusionar en un 40% tu ACOS base matemáticamente"], correctAnswer: 0, explanation: "El tráfico no deseado (ej. buscar segunda mano) se corta de raíz con Negative Keywords, liberando capital o wallet para tu verdadera audiencia que busca tu Ítem Cero KM.", difficulty: "dificil" },
  { question: "En un escenario Programático de Display / Performance transversal, un sistema robusto nativo o algorítmico de 'Pacing' asegura fuertemente:", options: ["Pausar y blindar totalmente en banda baja hasta validar el scoring total en tu tarjeta local confirmando saldo de origen", "Reducir y comprimir audios, acelerando metadatos para optimizar peso multimedia estricto y banda de impacto", "Distribuir e inyectar progresivamente consumos monetarios durante el transcurso lineal dictaminado con el fin de evitar quemar y quedarse sin el grueso presupuestal de la cuenta en las frenéticas primeras horas de mañana o picos", "Registrar y neutralizar temporalmente el frenético clic o las intenciones maliciosas de clicks bots invalidando pulsaciones rápidas repetidas por IP"], correctAnswer: 2, explanation: "El 'Pacing' orquesta un presupuesto diario ej:$1000 en todo tu día para que a las 5PM aún tengas alcance activo si alguien te busca para comprar, y no gastarlo a las 11AM limitando presencia vespertina.", difficulty: "dificil" },
  { question: "¿A qué denominamos métricamente la variable y ratio de Venta o 'Conversión Incremental' asociada unívocamente tras arrancar las campañas experimentales?", options: ["Las estimaciones macro diarias y brutas proyectadas a 1 año fiscal sin interrupción lineal basada en picos de Cybermonday pasados", "Decodifica el lote de compras logradas en alza total y puramente gracias a los anuncios en Ads, aislando qué no habrían ocurrido orgánicamente solas o si detuvieses abruptamente la inversión", "Se adjudica y extrapola todas las ventas hechas por tus competidores por la causa directa indirecta y tracción de rebote hacia tus anuncios parpadeantes", "Alude al crecimiento estricto orgánico nominal e indirecto de comisiones que cobra toda la plataforma por tu uso del modelo FULL de envíos gratuitos obligatorios de retención"], correctAnswer: 1, explanation: "La Incrementabilidad aísla tu canibalismo: responde a la máxima interrogante del marketer: '¿Hubieran comprado de todos modos?'. Mide qué plus y margen real genuino originó la campaña aislada que ni hubiera ocurrido per se. ROAS es solo la foto general; Incrementabilidad es el valor verdadero ganado.", difficulty: "dificil" }
];
